apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats-streaming:0.17.0
          # Arguments to run when container is up
          # Available commands in https://hub.docker.com/_/nats-streaming -> commands section
          args: [
              # Use port for clients (default: 4222)
              '-p',
              '4222',
              # Use port for http monitoring
              '-m',
              '8222',
              # Interval at which server sends heartbeat to a client
              '-hbi',
              '5s',
              # How long server waits for a heartbeat response
              '-hbt',
              '5s',
              # Number of failed heartbeats before server closes the client connection
              '-hbf',
              '2',
              # Enable STAN debugging output
              '-SD',
              # Cluster ID (default: test-cluster)
              '-cid',
              'bti',
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: nats-srv
spec:
  selector:
    app: nats
  ports:
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: monitoring
      protocol: TCP
      port: 8222
      targetPort: 8222
